### ISSUE TITLE
mail_see_recipients

### ISSUE THREAD

**Issue by yk2kus** [bistaray/odoo-apps#3]
No support for latin chars "subject":
why convert to [str](https://github.com/bistaray/odoo-apps/blob/10.0/mail_see_recipients/wizard/mail_compose_message.py#L17)
result['model'] = str(self._context.get('default_model'))
breaks for non-ascii chars

**Comment by gurneyalex** [comment]
I got this on my first tryout of the module:
```
Traceback (most recent call last):
  File "/opt/odoo/src/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/src/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/src/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/src/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/src/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/src/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/src/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/src/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/src/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/src/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/external-src/bistaray-odoo-apps/mail_see_recipients/wizard/mail_compose_message.py", line 17, in default_get
    result['subject'] = str(self._context.get('sub')) # updated default value for subject
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
```

**Comment by gurneyalex** [comment]
patch proposed
